apiVersion: apps/v1
kind: Deployment
metadata:
  name: chk1
  namespace: cal
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3 
  revisionHistoryLimit: 50
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.2-alpine
        ports:
        - containerPort: 80
